# Generated by Django 3.1.2 on 2020-10-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bricks",
            field=models.IntegerField(default=100, verbose_name="bricks"),
        ),
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.IntegerField(default=0, verbose_name="rating"),
        ),
    ]
