# Generated by Django 3.1.2 on 2020-10-11 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20201011_1005"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pig",
            name="upgrade_started",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="upgrade started"
            ),
        ),
        migrations.AlterField(
            model_name="pig",
            name="upgrade_time",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="upgrade time",
            ),
        ),
    ]
