# Generated by Django 3.1.2 on 2020-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201011_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='name',
            field=models.CharField(default='default pig', max_length=40),
        ),
    ]
