# Generated by Django 3.1.2 on 2020-10-12 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201012_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig',
            name='upgrade_time',
            field=models.DurationField(default=datetime.timedelta(0, 2), verbose_name='upgrade time'),
        ),
    ]
