# Generated by Django 3.1.2 on 2020-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201012_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='result',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='result'),
        ),
    ]
