# Generated by Django 3.1.2 on 2020-10-14 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201014_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='preparation_time',
            field=models.TimeField(blank=True, default=datetime.timedelta(0, 30), null=True, verbose_name='preparation time'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='result',
            field=models.CharField(blank=True, default='active', max_length=24, null=True, verbose_name='result'),
        ),
    ]
