# Generated by Django 3.1.2 on 2020-10-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201014_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
