# Generated by Django 3.1.2 on 2020-10-14 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201014_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
