# Generated by Django 3.1.2 on 2020-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201014_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='upgrade_cost',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='raid',
            name='preparation_time',
            field=models.TimeField(blank=True, default='00:00:05', null=True, verbose_name='preparation time'),
        ),
    ]
