version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  celery:
    build: ./
    command: celery -A WarPigs worker -l INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - rabbitmq
  celery-beat:
    build: ./
    command: celery -A WarPigs beat -l INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - rabbitmq
  flower:
    build: ./
    command: flower -A WarPigs --port=5555 --broker=amqp://user:password@rabbitmq:5672
    ports:
      - 5555:5555
    depends_on:
      - web
      - rabbitmq
      - celery